### PR TITLE
removed depth dimension from e1f and e2f in orca_names.py

### PR DESCRIPTION
**Pull request by jk-rieck**

### CODE REVIEW

**Comment by jk-rieck** [comment]
I have no idea, why the checks failed...

**Comment by jk-rieck** [comment]
rebased the branch to the newest version of `willirath:master`, maybe this helps....

**Comment by jk-rieck** [comment]
Apparently it did not help...

**Comment by willirath** [comment]
It's a style issue. The flake part of the job fails: https://travis-ci.org/willirath/xorca/jobs/521715746#L889

**Comment by willirath** [comment]
I'll merge this, because the failing check is unrelated.

**Pull request merged**
